### ISSUE TITLE
Establish a directory for secrets and have a script to generate them

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/os-base#5]
Ideally ```$HOME/secrets``` for any generated rpc passwords and generated seeds.

## Subtasks

- [ ] Create ***/etc/init.d*** script which generates secrets for comms between bitcoind and lnd  (Add to image)
- [ ] Symlink ***/etc/init.d*** script into runlevel 2 ***/etc/rc2.d*** (suggestions welcome). Add this to the image
- [ ] Add in support for writing to config files into the scripts
- [ ] check that the config files are actually useful

## Optional

Encrypt them (but also how do we use the key to decrypt them is something we need to work out)

## Expected Result

When we flash the SD card and run for the first time we should see all the secrets in ```$HOME/secrets```
